---
title: "Business Plots"
author: "Isolde B, Emiel C, Ruben V, Yves S"
date: "7-7-2021"
output: html_document
---

```{r setup, include=FALSE}
#Import files
knitr::opts_chunk$set(echo = TRUE)
source("boxplot.R", local = knitr::knit_global())
source("hist.R", local = knitr::knit_global())
source("piechart.R", local = knitr::knit_global())
source("gaugechart.R", local = knitr::knit_global())
source("spiderchart.R", local = knitr::knit_global())
source("bar.R", local = knitr::knit_global())
source("line.R", local = knitr::knit_global())
source("scatter.R", local = knitr::knit_global())
source("multipleline.R", local = knitr::knit_global())
source("multiplescaleline.R", local = knitr::knit_global())
source("treemap.R", local = knitr::knit_global())
source("formatobject.R", local = knitr::knit_global())
source("dualaxesline.R", local = knitr::knit_global())
source("dualaxesscatter.R", local = knitr::knit_global())
source("multiplescatter.R", local = knitr::knit_global())
source("barwithline.R", local = knitr::knit_global())
#Variable Declaration

#Data
filepath = "./YearReport.csv"
x_axis = "Year"
y_axis = "Quota"
y_axes <- c("Quota","Incidents","Complatins")
plot_title = "Annual quota"

#Layout
layout_file <- formatobject("./formatobject.csv")
colors <- extract_data_formatobject(formatobject=layout_file, "colors")
line_type <- extract_data_formatobject(formatobject=layout_file, "lineType")
symbol <- extract_data_formatobject(formatobject=layout_file, "pointShape")
auto_fit <- extract_data_formatobject(formatobject=layout_file, "autoFit")
lwd <- extract_data_formatobject(formatobject=layout_file, "lineWidth")
legend_pos <- extract_data_formatobject(formatobject=layout_file, "legendPosition")


print(colors)
#0, square
#1, circle
#2, triangle point up
#3, plus
#4, cross
#5, diamond
#6, triangle point down
#7, square cross
#8, star
#9, diamond plus
#10, circle plus
#11, triangles up and down
#12, square plus
#13, circle cross
#14, square and triangle down
#15, filled square
#16, filled circle
#17, filled triangle point-up
#18, filled diamond
#19, solid circle
#20, bullet (smaller circle)
#21, filled circle 
#22, filled square 
#23, filled diamond 
#24, filled triangle point-up 
#25, filled triangle point down 


```

## Scatter Plot
```{r scatter, echo=FALSE}
scatter(filepath, x_axis, y_axis, symbol[[1]], auto_fit, colors[[1]], colors[[2]])
```

## Line Plot
```{r line, echo=FALSE}
line(filepath, x_axis, y_axis, symbol[[1]], line_type[[1]], auto_fit, colors[[1]], colors[[2]])
```

## Horizontal Bar Plot
```{r horbar, echo=FALSE}
bar(filepath, x_axis, y_axis ,TRUE, FALSE, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Vertical Bar Plot
```{r verbar, echo=FALSE}
bar(filepath, x_axis, y_axis ,FALSE, FALSE, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Stacked Bar Plot
```{r stacked, echo=FALSE}
bar(filepath, x_axis, y_axis ,FALSE, TRUE, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Histogram
```{r histogram, echo=FALSE}
histogram(filepath, y_axis, TRUE, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Boxplot
```{r boxplot, echo=FALSE}
boxplt(filepath, y_axes, symbol[[1]], TRUE, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Piechart
```{r piechart, echo=FALSE}
piechart(filepath, plot_title, x_axis, y_axis, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Spiderchart
```{r spiderchart, echo=FALSE}
spiderchart(filepath, x_axis, y_axis, plot_title, lwd, line_type, lwd/2, colors[[1]], colors[[2]], colors[[3]], colors[[4]])
```

## gaugechart
```{r gaugachart, echo=FALSE}
gaugechart(25, 100, "indicator", "gauge+number", "Visitors inside", lwd*4, lwd/2, lwd/2, lwd, lwd/2, "Arial", colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Multiple lines
```{r multiline, echo=FALSE}
multiline(filepath, x_axis , y_axes, legend_pos, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Multiple scale lines
```{r multiscaleline, echo=FALSE}
multiscaleline(filepath, x_axis , y_axes, legend_pos, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Treemap
```{r treemap, echo=FALSE}
create_treemap(filepath, x_axis , y_axis, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Dual Axes
```{r dualaxes, echo=FALSE}
dualaxes(filepath, x_axis , y_axes, legend_pos, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Dual Ax Scatter plot
```{r dualaxscatter, echo=FALSE}
dualaxscatter(filepath, x_axis , y_axes, legend_pos, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## multiple Scatter plot
```{r multiscatter, echo=FALSE}
multiscatter(filepath, x_axis , y_axes, legend_pos, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```

## Bar with line plot
```{r barwithline, echo=FALSE}
barwithline(filepath, x_axis , y_axes, line_type, legend_pos, colors[[1]], colors[[2]], colors[[3]], colors[[4]], colors[[5]], colors[[6]])
```
